FROM golangci/golangci-lint AS lint
RUN which golangci-lint

FROM golang:1.14-buster

# chinese mirror for linux
COPY sources.list /etc/apt/sources.list
RUN apt-get update

ENV CGO_ENABLED=0

# lint
COPY --from=lint /usr/bin/golangci-lint /go/bin/golangci-lint

# chinese mirror for go packages
RUN go env -w GOPROXY=https://goproxy.cn,direct

# debugger tool
RUN go get -u github.com/go-delve/delve/cmd/dlv

ENV GO111MODULE=on

# gobay
RUN go get github.com/shanbay/gobay/cmd/gobay

# ent orm
RUN go get github.com/facebook/ent/cmd/entc@v0.4.0

# grpc
RUN apt-get install protobuf-compiler -y
RUN go get -u google.golang.org/grpc
RUN go get -u github.com/gogo/protobuf/protoc-gen-gofast
RUN go get -u github.com/golang/mock/mockgen

# tests
RUN go get -u github.com/cweill/gotests/

# test coverage
RUN go get github.com/wadey/gocovmerge
RUN go get github.com/axw/gocov/...
RUN go get github.com/AlekSi/gocov-xml

# oapi-codegen
RUN wget https://github.com/shanbay/oapi-codegen/releases/download/v1.5.1/oapi-codegen_1.5.1_linux_amd64 -O /usr/local/bin/oapi-codegen && chmod +x /usr/local/bin/oapi-codegen

WORKDIR /go/src/app

